server:
  host: "127.0.0.1"
  port: 8080
  name: "unknown"
  mode: "Dev"

mysql:
  dataSourceName: "root:mgh99999@(192.168.44.100:3306)/blog?charset=utf8mb4&parseTime=true&loc=Local"
  maxOpenConns: 20
  maxIdleConns: 10

